### ISSUE TITLE
[Feature] Use premium streaming on XYZ platform with hardware encoding

### ISSUE THREAD

**Issue by kunalgrover05** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#132]
**Is your feature request related to a problem? Please describe.**
TSD today only supports premium streaming using Raspberry pi hardware encoding. I am on a different machine which supports hardware encoding, I would like to use premium streaming. 

**Describe the solution you'd like**
Premium H264 streaming support for other platforms like: Intel / AMD on-board graphs, Nvidia graphs etc. 

**Describe alternatives you've considered**
Using 0.1 FPS streaming supported today. It is too inefficient for both detection and viewing. 

**Additional context**
NA

**Comment by kunalgrover05** [comment]
I am proposing a docker image which would support premium streaming on any platform which has FFMPEG Hardware encoding support. It currently **breaks Octoprint** because of the different input expected by Octoprint but it should be possible to also add FFServer streaming to fix it back: http://trac.ffmpeg.org/wiki/ffserver

```
version: '2.4'
 
services:
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 80:80
      - 8090:8080
    volumes:
     - octoprint:/octoprint
    devices:
     - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
     - JANUS_SERVER=<Your Hostname>
  
  janus:
    restart: unless-stopped
    # Uses host networking because it uses a lot of ports for UDP streaming. 
    network_mode: host
    image: thespaghettidetective/janus:ubuntu
    command: sh -c "/opt/janus/bin/janus"
 
   ffmpeg:
      # Replace with your image with the appropriate HW acceleration build
      image: jrottenberg/ffmpeg:4.1-vaapi
      devices:
        # Your camera goes here
        - /dev/video2:/dev/video0
      # 8004 is the port in the Janus plugin config
      command: "-f v4l2 -framerate 25 -stats -i /dev/video0 -c:v libx264 -preset ultrafast -f rtp rtp://server:8004?pkt_size=1300"

volumes:
  octoprint:

```
